version: "3.8"


networks:
 geo_db_network:
    name: "geo_db_network"

services:
 geo_db_master:
    restart: unless-stopped
    image: postgres:16.0-alpine3.18
    volumes:
      - ./.container_data/database/postgres/data:/var/lib/postgresql/data
      - ./db/init-up.sql:/docker-entrypoint-initdb.d/init.up.sql
    # ports:
    #   - 5440:5432
    networks:
      - geo_db_network
    environment:
       PGDATA: /var/lib/postgresql/data
       POSTGRES_USER: ${POSTGRES_USER}
       PGUSER: ${PGUSER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: geo
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
 geo_pool:
    image: bitnami/pgbouncer
    restart: unless-stopped
    ports:
      - 6437:6432
    networks:
      - geo_db_network
      - databases_network
    environment:
      POSTGRESQL_HOST: geo_db_master
      POSTGRESQL_USERNAME: ${POSTGRES_USER}
      POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/pgbouncer/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
      - ./docker/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt
    depends_on:
      geo_db_master:
        condition: service_healthy 